### ISSUE TITLE
Update to NeoForge

### ISSUE THREAD

**Issue by Quantum-mutnauQ** [dimadencep/jlmi#2]
Hello dima-dencep,
I wanted to kindly request if you could consider updating the mod to version 1.21.1 with NeoForge.

**Comment by dima-dencep** [comment]
NeoForge doesn't require this, everything works out of the box

**Comment by Quantum-mutnauQ** [comment]
Hi Dima-Dencep,
I'm having trouble joining a server with all my mods installed. I need to go through each one to identify which mod is causing the issue.

An example of a problematic mod is [Placebo](https://www.curseforge.com/minecraft/mc-mods/placebo/files). Removing it allows me to join the server without issues.

I get this message:
![grafik](https://github.com/user-attachments/assets/90ec1e68-ce69-43ff-b55b-59c1df6b3d8f)

**Comment by dima-dencep** [comment]
That's the way it's supposed to be

**Comment by Quantum-mutnauQ** [comment]
Thank you for your prompt response! I spent half the day working on my own mod, and I'm pleased to say that it's turned out great.
